# Site settings
title: jsdev.org

description: Opensource project with notes for development modern javascript projects

keywords: javascript, js, node.js, react, vue.js, angular, typescript, docker, linux, kubernetes

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jsdev.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap